---
- name: Provision localhost
  hosts: localhost
  connection: local
  vars:
    git_username: ""
    git_email: ""

  pre_tasks:
    - name: Update and upgrade apt system packages
      become: true
      apt:
        upgrade: "yes" # In addition to yes and no you can use dist, full, or safe, therefore it is a string
        update_cache: yes
    - name: Install additional packages
      become: true
      package:
        name:
          - emacs
          - fonts-powerline
        state: present
  roles:
    - role: gantsign.oh-my-zsh
      oh_my_zsh_theme: agnoster
      oh_my_zsh_plugins:
        - git
      users:
        - username: "{{ ansible_env.USER }}"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_env.USER }}"
          visual_studio_code_extensions: []
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings:
            {
              "editor.formatOnSave": true,
              "editor.renderWhitespace": "boundary",
              "terminal.integrated.fontFamily": "Menlo for Powerline",
              "terminal.integrated.shell.linux": "/usr/bin/zsh",
            }
  post_tasks:
    - name: Switch to zsh
      become: yes
      user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/zsh
      when: ansible_env.SHELL != '/usr/bin/zsh'
    - name: Install git
      import_tasks: git.yaml
    - name: Generate SSH key pair
      import_tasks: ssh.yaml
    - name: Configure VS Code
      import_tasks: fix-vs-code-fonts.yaml
    - name: Install OCaml
      import_tasks: ocaml.yaml
    - name: Add user to virtualbox group
      become: true
      user:
        name: "{{ ansible_env.USER }}"
        groups:
          - vboxsf
        append: yes
