---
- name: Provision localhost
  hosts: localhost
  connection: local
  vars:
    git_username: ""
    git_email: ""
    virtualenv_folder: ~/venv/python3
  pre_tasks:
    - name: Update and upgrade apt system packages
      become: true
      apt:
        upgrade: "yes" # In addition to yes and no you can use dist, full, or safe, therefore it is a string
        update_cache: yes
    - name: Install additional packages
      become: true
      package:
        name:
          - emacs
          - fonts-powerline
          - apt-transport-https
        state: present
    - name: Install python 3.x
      import_tasks: python.yaml
    - name: Install .Net
      import_tasks: dotnet.yaml
  roles:
    - role: gantsign.oh-my-zsh
      oh_my_zsh_theme: agnoster
      oh_my_zsh_plugins:
        - git
      users:
        - username: "{{ ansible_env.USER }}"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_env.USER }}"
          visual_studio_code_extensions:
            - ms-python.python
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings:
            {
              "editor.formatOnSave": true,
              "editor.renderWhitespace": "boundary",
              "terminal.integrated.fontFamily": "Menlo for Powerline",
              "terminal.integrated.shell.linux": "/usr/bin/zsh",
              "python.pythonPath": "{{ virtualenv_folder }}/bin/python",
              "python.linting.flake8Enabled": true,
              "python.linting.flake8Path": "{{ virtualenv_folder }}/flake8",
              "python.linting.enabled": false,
              "python.formatting.autopep8Path": "{{ virtualenv_folder }}/bin/autopep8",
              "python.defaultInterpreterPath": "{{ virtualenv_folder }}/bin/python",
            }
  post_tasks:
    - name: Switch to zsh
      become: yes
      user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/zsh
      when: ansible_env.SHELL != '/usr/bin/zsh'
    - name: Install git
      import_tasks: git.yaml
    - name: Generate SSH key pair
      import_tasks: ssh.yaml
    - name: Configure VS Code
      import_tasks: fix-vs-code-fonts.yaml
    - name: Install OCaml
      import_tasks: ocaml.yaml
    - name: Install Rider IDE
      import_tasks: rider-ide.yaml
    - name: Add user to virtualbox group
      become: true
      user:
        name: "{{ ansible_env.USER }}"
        groups:
          - vboxsf
        append: yes
